parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     3306
    database_name:     kitpages_cms
    database_user:     root
    database_password:

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:
    mailer_password:

    locale:             en

    secret:             ThisTokenIsNotSoSecretChangeIt

    email_contact:      "email@example.com"
    email_webmaster:    "email@example.com"

    base_url:           http://example.com
    google_analytics_ua: "UA-XXXX"