kitpages_cms:
    resource: "@KitpagesCmsBundle/Resources/config/routing.yml"
    prefix: "cms"

kitpages_file:
    resource: "@KitpagesFileBundle/Resources/config/routing.yml"
    prefix: "file"

app_kit_user:
    resource: "@AppUserBundle/Resources/config/routing.yml"
    prefix: "user"

app_kit_site:
    resource: "@AppSiteBundle/Resources/config/routing.yml"

