default:
    pattern:  /
    defaults: { _controller: AppSiteBundle:Default:index }

news:
    pattern:  /{_locale}/news
    defaults: { _controller: AppSiteBundle:Default:newsList, _locale: en }
    requirements:
        _locale: en|fr
contact_form:
    pattern:  /{_locale}/contact
    defaults: { _controller: AppSiteBundle:Default:contact, _locale: en }
    requirements:
        _locale: en|fr

contact_form_send:
    pattern:  /{_locale}/contact-send
    defaults: { _controller: AppSiteBundle:Default:contactSend, _locale: en }
    requirements:
        _locale: en|fr

page_news:
    pattern:  /{_locale}/news/{kitCmsBlockSlug}
    defaults: { _controller: AppSiteBundle:Default:news, _locale: en }
    requirements:
        _locale: en|fr

kitpages_cms_page_view_lang:
    pattern:  /{_locale}/cms/{id}/{urlTitle}
    defaults: { _controller: KitpagesCmsBundle:Page:view, _locale: fr }
    requirements:
        id: \d+
        _locale: en|fr
